# Generated by Django 3.0.7 on 2020-06-19 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host_Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('ip_address', models.GenericIPAddressField(default='192.168.1.100', unique=True)),
                ('ram', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('processor', models.IntegerField(null=True)),
                ('hdd', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('os', models.CharField(default='Windows', max_length=30)),
                ('descriptions', models.CharField(default='Lenovo M5', max_length=50)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Stopped', 'Stopped')], default='Running', max_length=10)),
                ('site', models.CharField(choices=[('Data_Center', 'DC'), ('Disater_Recovery', 'DR'), ('Far_DR', 'fDR')], default='DC', max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VM_Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('ip_address', models.GenericIPAddressField(default='192.168.1.100', unique=True)),
                ('ram', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('processor', models.IntegerField(null=True)),
                ('hdd', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('os', models.CharField(default='Windows', max_length=30)),
                ('descriptions', models.CharField(default='purpose', max_length=50)),
                ('app_owner', models.CharField(default='Imran', max_length=20)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Stopped', 'Stopped')], default='Running', max_length=10)),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='server.Host_Server')),
            ],
        ),
    ]
