# Generated by Django 3.0.7 on 2020-06-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_server',
            name='site',
            field=models.CharField(choices=[('Data Center', 'DC'), ('Disater Recovery', 'DR'), ('Far DR', 'fDR')], default='DC', max_length=16, null=True),
        ),
    ]
