# Generated by Django 3.0.7 on 2020-06-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20200622_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm_server',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='server.Host_Server', to_field='name'),
        ),
    ]
