# Generated by Django 3.0.7 on 2020-06-26 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20200622_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm_server',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='server.Host_Server'),
        ),
    ]
