# Generated by Django 3.0.7 on 2020-06-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20200626_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host_server',
            options={'verbose_name': 'Host Server', 'verbose_name_plural': 'Host Servers'},
        ),
        migrations.AlterModelOptions(
            name='vm_server',
            options={'verbose_name': 'VM Server', 'verbose_name_plural': 'VM Servers'},
        ),
    ]
