# Generated by Django 3.0.7 on 2020-07-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20200627_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_server',
            name='sn',
            field=models.CharField(default='', max_length=30, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='host_server',
            name='ip_address',
            field=models.GenericIPAddressField(default='192.168.1.100', unique=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='host_server',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Host Name'),
        ),
        migrations.AlterField(
            model_name='host_server',
            name='os',
            field=models.CharField(default='Windows', max_length=30, verbose_name='Operating System'),
        ),
        migrations.AlterField(
            model_name='vm_server',
            name='ip_address',
            field=models.GenericIPAddressField(default='192.168.1.100', unique=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='vm_server',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Server Name'),
        ),
        migrations.AlterField(
            model_name='vm_server',
            name='os',
            field=models.CharField(default='Windows', max_length=30, verbose_name='Operating System'),
        ),
    ]
