# Generated by Django 3.0.7 on 2020-07-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20200702_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_server',
            name='descriptions',
            field=models.CharField(default='', max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='host_server',
            name='hdd',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Hard Disk'),
        ),
        migrations.AlterField(
            model_name='host_server',
            name='processor',
            field=models.IntegerField(null=True, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='host_server',
            name='ram',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='vm_server',
            name='app_owner',
            field=models.CharField(default='Imran', max_length=20, verbose_name='Application Owner'),
        ),
        migrations.AlterField(
            model_name='vm_server',
            name='descriptions',
            field=models.CharField(default='', max_length=50, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='vm_server',
            name='hdd',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Hard Disk'),
        ),
        migrations.AlterField(
            model_name='vm_server',
            name='processor',
            field=models.IntegerField(null=True, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='vm_server',
            name='ram',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='RAM'),
        ),
    ]
